import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css"

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800', '900'], // Explicitly loading bolds
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
